services:
  composer:
    image: composer
    environment:
      - COMPOSER_CACHE_DIR=/app/var/composer/cache
    volumes:
      - .:/app
    profiles: ['tools']

  deptrac:
    build:
      context: ./docker/deptrac
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: deptrac
    profiles: ['tools']

  tests:
    build:
      context: ./docker/tests
    depends_on:
      - database
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
    profiles: ['tools']

  console:
    extends:
      service: fpm
    depends_on:
      - database
    entrypoint: bin/console
    profiles: ['tools']

  fpm:
    build:
      context: ./docker/php
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:52cc754834083c567c713f48561cb5422d8@database:5432/postgres?serverVersion=13&charset=utf8
    working_dir: /app
    volumes:
      - .:/app

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 52cc754834083c567c713f48561cb5422d8
    volumes:
      - ./var/postgresql:/var/lib/postgresql/data
