homepage:
  path: /
  controller: Infrastructure\Symfony\Controller\DecksController::index

decks:
  path: /
  controller: Infrastructure\Symfony\Controller\DecksController::index

create_deck:
  methods: POST
  path: /new
  controller: Infrastructure\Symfony\Controller\CreateDeckController::create

edit_deck:
  methods: GET
  path: /edit/{id}
  controller: Infrastructure\Symfony\Controller\EditDeckController::edit

add_card:
  methods: POST
  path: /edit/{deckId}/add
  controller: Infrastructure\Symfony\Controller\DeckCardsController::add

remove_card:
  methods: POST
  path: /edit/{deckId}/remove
  controller: Infrastructure\Symfony\Controller\DeckCardsController::remove

cards:
  path: /cards
  controller: Infrastructure\Symfony\Controller\CardsController::index
