homepage:
  path: /
  controller: Infrastructure\Symfony\Controller\DecksController::index

decks:
  path: /
  controller: Infrastructure\Symfony\Controller\DecksController::index

create_deck:
  methods: POST
  path: /new
  controller: Infrastructure\Symfony\Controller\CreateDeckController::create

edit_deck:
  methods: GET
  path: /deck/{id}
  controller: Infrastructure\Symfony\Controller\EditDeckController::edit

choose_card:
  methods: POST
  path: /deck/{deckId}
  controller: Infrastructure\Symfony\Controller\ChooseCardsController::choose

cards:
  path: /cards
  controller: Infrastructure\Symfony\Controller\CardsController::index
